/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sadeep
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_topic = new javax.swing.JLabel();
        jButton_student = new javax.swing.JButton();
        jButton_teacher = new javax.swing.JButton();
        jButton_subject = new javax.swing.JButton();
        jLabel_students = new javax.swing.JLabel();
        jLabel_teachers = new javax.swing.JLabel();
        jLabel_subjects = new javax.swing.JLabel();
        jButton_logout = new javax.swing.JButton();
        jLabel_background = new javax.swing.JLabel();
        jMenuBar_menubar = new javax.swing.JMenuBar();
        jMenu_navigation = new javax.swing.JMenu();
        jMenuItem_dashboard = new javax.swing.JMenuItem();
        jMenuItem_logout = new javax.swing.JMenuItem();
        jMenuItem_close = new javax.swing.JMenuItem();
        jMenu_about = new javax.swing.JMenu();
        jMenuItem_info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_topic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_topic.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_topic.setText("SDR SCHOOL MANAGEMENT SYSTEM DASHBOARD");
        jPanel1.add(jLabel_topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jButton_student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/Students.png"))); // NOI18N
        jButton_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_studentActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 140));

        jButton_teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/Teachers.png"))); // NOI18N
        jButton_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_teacherActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, 140));

        jButton_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/Subjects.png"))); // NOI18N
        jButton_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_subjectActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 140, 140));

        jLabel_students.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_students.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_students.setText("STUDENTS");
        jPanel1.add(jLabel_students, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel_teachers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_teachers.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_teachers.setText("TEACHERS");
        jPanel1.add(jLabel_teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabel_subjects.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_subjects.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_subjects.setText("SUBJECTS");
        jPanel1.add(jLabel_subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/logout.png"))); // NOI18N
        jButton_logout.setText("Logout");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, 30));

        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/dashboard_background.png"))); // NOI18N
        jLabel_background.setText("jLabel2");
        jPanel1.add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, -34, 780, 510));

        jMenu_navigation.setText("Navigation");

        jMenuItem_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/home.png"))); // NOI18N
        jMenuItem_dashboard.setText("Dashboard");
        jMenuItem_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_dashboardActionPerformed(evt);
            }
        });
        jMenu_navigation.add(jMenuItem_dashboard);

        jMenuItem_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/logout.png"))); // NOI18N
        jMenuItem_logout.setText("Logout");
        jMenuItem_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_logoutActionPerformed(evt);
            }
        });
        jMenu_navigation.add(jMenuItem_logout);

        jMenuItem_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/cancel.png"))); // NOI18N
        jMenuItem_close.setText("Close");
        jMenuItem_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_closeActionPerformed(evt);
            }
        });
        jMenu_navigation.add(jMenuItem_close);

        jMenuBar_menubar.add(jMenu_navigation);

        jMenu_about.setText("About");

        jMenuItem_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/about.png"))); // NOI18N
        jMenuItem_info.setText("Info");
        jMenuItem_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_infoActionPerformed(evt);
            }
        });
        jMenu_about.add(jMenuItem_info);

        jMenuBar_menubar.add(jMenu_about);

        setJMenuBar(jMenuBar_menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(779, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_dashboardActionPerformed
        // TODO add your handling code here:
        dashboard dFrame = new dashboard();
        dFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_dashboardActionPerformed

    private void jMenuItem_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_closeActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(this, "Are you sure you want to close the application?", "Cancel Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
        dispose();
        }
    }//GEN-LAST:event_jMenuItem_closeActionPerformed

    private void jButton_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_teacherActionPerformed
        // TODO add your handling code here:
        teachers tFrame = null;
        try {
            tFrame = new teachers();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        tFrame.setVisible(true);
        dispose();
    
    }//GEN-LAST:event_jButton_teacherActionPerformed

    private void jMenuItem_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_infoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Created by S.D.R.");
    }//GEN-LAST:event_jMenuItem_infoActionPerformed

    private void jMenuItem_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_logoutActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
        login lFrame = new login();
        lFrame.setVisible(true);
        dispose();
}

    }//GEN-LAST:event_jMenuItem_logoutActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
        login lFrame = new login();
        lFrame.setVisible(true);
        dispose();
}

    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_studentActionPerformed
        // TODO add your handling code here:
        students stFrame = null;
        try {
            stFrame = new students();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        stFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_studentActionPerformed

    private void jButton_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_subjectActionPerformed
        // TODO add your handling code here:
        subjects subFrame = new subjects();
        subFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_subjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_student;
    private javax.swing.JButton jButton_subject;
    private javax.swing.JButton jButton_teacher;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_students;
    private javax.swing.JLabel jLabel_subjects;
    private javax.swing.JLabel jLabel_teachers;
    private javax.swing.JLabel jLabel_topic;
    private javax.swing.JMenuBar jMenuBar_menubar;
    private javax.swing.JMenuItem jMenuItem_close;
    private javax.swing.JMenuItem jMenuItem_dashboard;
    private javax.swing.JMenuItem jMenuItem_info;
    private javax.swing.JMenuItem jMenuItem_logout;
    private javax.swing.JMenu jMenu_about;
    private javax.swing.JMenu jMenu_navigation;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
