/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Sadeep
 */
public class loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public loading() {
        initComponents();
        loading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_topic1 = new javax.swing.JLabel();
        jLabel_topic2 = new javax.swing.JLabel();
        jLabel_loading = new javax.swing.JLabel();
        jLabel_processPercentage = new javax.swing.JLabel();
        jProgressBar_loading = new javax.swing.JProgressBar();
        jLabel_schoolPic = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_topic1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_topic1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_topic1.setText("WELCOME");
        jPanel1.add(jLabel_topic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel_topic2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_topic2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_topic2.setText("SDR SCHOOL MANAGEMENT SYSTEM");
        jPanel1.add(jLabel_topic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel_loading.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel_loading.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_loading.setText("Loading...");
        jPanel1.add(jLabel_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 110, -1));

        jLabel_processPercentage.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel_processPercentage.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_processPercentage.setText("0%");
        jPanel1.add(jLabel_processPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));
        jPanel1.add(jProgressBar_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 400, 20));

        jLabel_schoolPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/school.png"))); // NOI18N
        jPanel1.add(jLabel_schoolPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, 160));

        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/loading_background.png"))); // NOI18N
        jLabel_background.setText("jLabel3");
        jPanel1.add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(611, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_loading;
    public static javax.swing.JLabel jLabel_processPercentage;
    private javax.swing.JLabel jLabel_schoolPic;
    private javax.swing.JLabel jLabel_topic1;
    private javax.swing.JLabel jLabel_topic2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar_loading;
    // End of variables declaration//GEN-END:variables

private void loading(){
    new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                for (int i = 0; i < 101; i++) {
                    jProgressBar_loading.setValue(i);
                    jLabel_processPercentage.setText(i + "%");
                    Thread.sleep(45);
                }
                // Once loading is complete, dispose the loading frame and open the login frame
                dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new login().setVisible(true);
                    }
                });
            } catch (Exception e) {
            }
        }
    }).start();
}
}
