/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Util.databaseConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Sadeep
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    PreparedStatement pst;
    ResultSet rs;
    private Connection con;
    
    public login() {
        super("Login");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_background = new javax.swing.JPanel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jTextField_username = new javax.swing.JTextField();
        jButton_login = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel1_topic = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username.setText("Username");
        jPanel_background.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("Password");
        jPanel_background.add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
        jPanel_background.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, -1));
        jPanel_background.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, -1));

        jButton_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/login.png"))); // NOI18N
        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        jPanel_background.add(jButton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 99, -1));

        jButton_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/cancel.png"))); // NOI18N
        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        jPanel_background.add(jButton_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel1_topic.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1_topic.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_topic.setText("Login");
        jPanel_background.add(jLabel1_topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pics/login-gradient-background.png"))); // NOI18N
        jLabel_background.setMaximumSize(new java.awt.Dimension(420, 330));
        jLabel_background.setMinimumSize(new java.awt.Dimension(420, 330));
        jLabel_background.setPreferredSize(new java.awt.Dimension(420, 330));
        jPanel_background.add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(629, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(this, "Are you sure you want to close the application?", "Cancel Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
        dispose();
        }
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
    try {
        // Initialize the database connection
        con = databaseConnection.getDBConnection(); 
        
        // Retrieve username and password from text fields
        String username = jTextField_username.getText();
        String password = new String(jPasswordField_password.getPassword());
        
        // Prepare the SQL query
        pst = con.prepareStatement("SELECT * FROM login WHERE Username = ? AND Password = ?");
        pst.setString(1, username);
        pst.setString(2, password);
        
        // Execute the query
        rs = pst.executeQuery();
        
        // Check the results
        if (rs.next()) {
            // If the login is successful, open the DashboardFrame and close this one
            dashboard dFrame = new dashboard();
            dFrame.setVisible(true);
            dispose();
        } else if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "The fields cannot be empty!");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
        }
        
        // Close the connection
        con.close();
    } catch (SQLException | ClassNotFoundException e1) {
        e1.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database connection error!");
    }
    }//GEN-LAST:event_jButton_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1_topic;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel_background;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
